### ISSUE TITLE
Just says "unknown error"

### ISSUE THREAD

**Issue by kubo6472** [alariej/quadrix#21]
...when logging in.
HS fed result: https://fed.mau.dev/tjm.sk
I downloaded the app 2day from the google play store, was instructed to report here.

**Comment by alariej** [comment]
Thanks for reporting. I see from the JSON response that you are using a Conduit homeserver. Quadrix has been so far tested with Synapse only, so that could be the problem. Did you try entering the server name as "m.tjm.sk" instead of "tjm.sk" when attempting to login with Quadrix? Would you have a test account on tjm.sk that I can use to investigate the problem? Otherwise I would either have to install Conduit myself, or try to find a public Conduit server which allows registrations.

**Comment by kubo6472** [comment]
No I haven't tried that. Thanks, that helped. I have a suggestion or two right away: why have option to use two different types of logging in (with two or three inputs respectively, yet the error is so general. In the app, you have an option to delete your matrix account, yet no option to move the chat input box (where you type) to bottom, or switch colors to dark mode. I understand these might not be implemented yet, but it seems like the app is targetting a very small and specific userbase. Or like how long is this around? I assume a bit, definitely. Anyway, I'm closing this, since the original issue has been solved. But it doesn't honor .well-known/matrix/client on the root domain, like all the other clients do.

**Comment by alariej** [comment]
Thanks for the suggestions. Quadrix is fairly new and still has a very small user base, there's still lots of things to do. Error feedback is not great at the moment, and the UI is very much static, without any configuration options. That should get better with time. I did get a test account on conduit.rs, which obviously uses Conduit, and I can confirm that Quadrix produces an error at login when entering "conduit.rs" in the server field. As you wrote, it fails at picking up the actual server domain from the .well-known file. So I'll work on solving that so that the next Quadrix release can have a fix for it.

**Comment by kubo6472** [comment]
Thank you very much. My HS is frequently offline (as e.g. right now) so it wouldn't really help you debug something, if it will just not respond at all. I'm sure you understand. Test acc on conduit.rs is great news. Anyway, good luck to you and for the next release. I'll retract my review from play store, and revisit this, when it will have some more features. Thanks for your time and help. Have a great day.

**Comment by alariej** [comment]
@kubo6472 For info, I have released version 1.4.5 of Quadrix, with support for the `.well-known` API call (commit: https://github.com/alariej/quadrix/commit/b3d69e4aab9a6801d38331bb56647ae5cfe49907). I have tested it successfully on the _conduit.rs_ Matrix server. You should now be able to login on your homeserver with just the domain name. Let me know if that works for you. Please note that as I was doing tests on _conduit.rs_, I noticed some other issues, probably related to a slightly different implementation of the Matrix protocol between Conduit and Synapse. Please open new issues if you come across bugs. Thanks.
